postgresql:
  build: postgres-dockerfile
  ports:
   - "5432:5432"
  env_file:
   - ./postgres-dockerfile/postgres.env
elasticsearch:
  image: elasticsearch:1.7.1
  ports:
   - "9200:9200"
   - "9300:9300"